---
title: "Computer Lab 1"
author: "Martynas Lukosevicius, Alejo Perez Gomez, Zahra Jalil Pour"
date: "03/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

### 1 
It is not possible to represent exact 1/3 and 1/12 in binary. As a result it is rounded towards nearest computer float and in R its equal to 0.33333333333333331 and 0.083333333333333329 respectively.

### 2

Instead of writing  ``if(x1 - x2 == 1/12)`` it should be written ``if(isTRUE(all.equal(x1-x2,1/12)))``. In this case this equation will return TRUE.


## Question 4

### 1

is it he case when n = k = 0 or n > 0, k = 0 ?

```{r}
n <- 1000
k <- 800
prod(1:n) / (prod(1:k) * prod(1:(n-k)))
prod((k+1):n) / prod(1:(n-k))
prod(((k+1):n) / (1:(n-k)))
```


### 2
```{r, echo=FALSE,  fig.height= 6}
#n <- c(20:100)

calc1 <- function(n,k){
k <- n - k
 return(prod(1:n) / (prod(1:k) * prod(1:(n-k)))) 
}
calc2 <- function(n,k){
  k <- n - k
 return(prod((k+1):n) / prod(1:(n-k))) 
}
calc3 <- function(n,k){
  k <- n - k
 return(prod(((k+1):n) / (1:(n-k)))) 
}

n <- c(20:400)
k <- 20

y <-  sapply(n, calc1, k = k)
y2 <-  sapply(n, calc2, k = k)
y3 <-  sapply(n, calc3, k = k)
par(mfrow=c(3,1))
plot(n,y, type = "l", main = "A , k =n-20" , ylab = "y")
plot(n,y2, type = "l", main = "B , k =n-20", ylab = "y")
plot(n, y3, type = "l", main = "C , k =n-20", ylab = "y")
```


```{r, echo=FALSE,  fig.height= 6}
calc1 <- function(n,k){
 return(prod(1:n) / (prod(1:k) * prod(1:(n-k)))) 
}
calc2 <- function(n,k){
 return(prod((k+1):n) / prod(1:(n-k))) 
}
calc3 <- function(n,k){
 return(prod(((k+1):n) / (1:(n-k)))) 
}

n <- c(20:400)
k <- 20

y <-  sapply(n, calc1, k = k)
y2 <-  sapply(n, calc2, k = k)
y3 <-  sapply(n, calc3, k = k)
par(mfrow=c(3,1))

plot(n,y, type = "l", main = "k =n-20", sub =  "A  " , ylab = "y")
plot(n,y2, type = "l", sub = "B , k =n-20", ylab = "y")
plot(n, y3, type = "l", sub = "C , k =n-20", ylab = "y")

```

### 3
