---
title: "Computer Lab 4"
author: "Martynas Lukosevicius"
date: "25/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2. Gibbs sampling

### 1.
```{r}
load("chemical.RData")  # read csv file 
plot(X,Y)
```

linear? IDK


### 2.

if $Y_i \sim N(\mu_i,0.2)$

so $p(\vec Y | \vec \mu)$ is multivariate gausian 

$$ p(\vec Y | \vec \mu, \Sigma) \sim \frac {1} {\sqrt{(2 \pi)^n |\Sigma|} } e^{- \frac 1 2 (Y- \vec \mu)^T \Sigma^{-1} (Y-\vec \mu)}$$
where $\Sigma = 0.2 I$

likelihood of $p(\vec Y | \vec \mu)$ is 
$$p(\vec Y | \vec \mu) = {(2\pi\sigma^2)^{-\frac{n}{2}}} exp[{-\frac{\sum^n_{i=2} (y_i - \mu_{i})^2}{2\sigma^2}}]$$


prior:

$$p(\vec \mu) = {(2\pi\sigma^2)^{-\frac{n}{2}}} exp[{-\frac{\sum^n_{i=2} (\mu_i - \mu_{i-1})^2}{2\sigma^2}}] p(\mu_1)$$

where: $\sigma = 0.2$ and $p(\mu_1) = 1$



posterior$\propto$


$$p(\vec \mu | \vec Y) \propto  exp[{-\frac{\sum^n_{i=2} (\mu_i - \mu_{i-1})^2}{2\sigma^2}}] * exp[{-\frac{\sum^n_{i=1} (y_i - \mu_{i})^2}{2\sigma^2}}] = exp[{-\frac{ (y_1 - \mu_1)^2+\sum^n_{i=2} (\mu_i - \mu_{i-1})^2 + (y_i - \mu_{i})^2}{2\sigma^2}}]$$


when

$$p(\mu_1|\vec \mu_{-1,}, \vec Y) \propto exp[ -\frac 1 {2 \sigma^2} [(\mu_1-\mu_2)^2 + (\mu_1 - y_1)^2]] = exp[- \frac {1}{\sigma^2} [\mu_1 - \frac{\mu_2 + y_1}{2}]^2] \sim N(\frac{\mu_2 + y_1}{2}, \frac {\sigma^2}{2})$$

$$p(\mu_1|\vec \mu_{-1,}, \vec Y) \propto exp[ -\frac 1 {2 \sigma^2} [(\mu_{n-1}-\mu_n)^2 + (\mu_n - y_n)^2]] = exp[- \frac {1}{\sigma^2} [\mu_n - \frac{\mu_{n-1} + y_n}{2}]^2] \sim N(\frac{\mu_{n-1} + y_n}{2}, \frac {\sigma^2}{2})$$

$$p(\mu_i|\vec \mu_{-i}, \vec Y) \propto exp[ -\frac 1 {2 \sigma^2} [(\mu_{i-1}-\mu_i)^2 + (\mu_i-\mu_{i+1})^2 + (\mu_i-y_i)^2] = exp[- \frac 3 {2\sigma^2} [\mu_i - \frac{\mu_{i-1}+ \mu_{i+1} + y_i}{3}]^2] \sim N(\frac{\mu_{i-1}+ \mu_{i+1} + y_i}{3}, \frac{\sigma^2}{3})$$
## 4.

```{r}
GibsSampler <- function(n,k){
  initx <- as.data.frame(t(rep(0,k)))
  for (i in 2:n) {
    mu <- unlist(initx[i-1, ])
    mu[1] <- rnorm(1,(mu[2]+Y[1])/2,0.2/2)
    for (j in 2:(k-1)) {
      mu[j] <- rnorm(1,(mu[j-1]+mu[j+1]+Y[j])/3,0.2/3)
    }
    mu[k] <- rnorm(1,(mu[k-1]+Y[k])/2,0.2/2)
    initx <- rbind(initx,mu)
  }
  return(initx)
}
```

```{r}
res <- GibsSampler(1000, length(X))

expectedmean <- unname(unlist(colSums(res/nrow(res))))
```

```{r}
plot(X,expectedmean,type = "l", col="red",ylab = "y")
lines(X,Y)
legend("bottomright", c("measured", "expected"), fill=c("black", "red"))
```

```{r}
plot(res[, 50], type="l")
```


No burn in interval? only initial value is 0 and later pretty much fluctuates... 